title: "Joan Of Arc Xavier"
logo: pic1.jpeg  # Ensure it's in the correct location
description: "Machine Learning | Deep Learning | Time Series Analysis | Data Analysis "
show_downloads: False
theme: jekyll-theme-minimal # cayman
github:
  is_project_page: false
