title: Joan Of Arc Xavier
# logo: /repo name/Joan_avatar.jpeg
logo: /joan-xavier/Joan_avatar.jpeg
description: PhD in Electrical Engineering | ML & Deep Learning | Time Series Analysis
show_downloads: False
theme: jekyll-theme-minimal
